<!DOCTYPE html>
<html>
<head>
    <title>Delay</title>
    <link rel="stylesheet" type="text/css" href="./TestPage.css" />
    <script src="./LoadPackages.js"></script>
    <script src="./TestPage.js"></script>
</head>
<body>
    <script>
        TestCase("writing a result to a not evaluated delay should success", function () {
            var x = CreateDelay();
            x.promise.SetResult(100);
            Assert(x.future.Result === 100);
        })
    </script>
    <script>
        TestCase("writing a result to an evaluated delay should success", function () {
            var x = CreateDelay();
            x.promise.SetResult(100);
            try {
                x.promise.SetResult(200);
                Assert(false);
            }
            catch (ex) {
                Assert(x.future.Result === 100);
            }
        })
    </script>
    <script>
        TestCase("a written succeeded result should be correctly redirected (1)", function () {
            var x = CreateDelay();
            var f1 = x.future.SucceededThen(function (value) {
                return value * 2;
            });
            var f2 = x.future.Then(function (value) {
                Assert(!DelayException.TestType(value));
                return value * 4;
            });
            x.promise.SetResult(100);
            Assert(f1.Result === 200);
            Assert(f2.Result === 400);
        })
    </script>
    <script>
        TestCase("a written succeeded result should be correctly redirected (2)", function () {
            var x = CreateDelay();
            var f1 = x.future.SucceededThen(function (value) {
                return CreateEvaluatedFuture(value * 2);
            });
            var f2 = x.future.Then(function (value) {
                Assert(!DelayException.TestType(value));
                return CreateEvaluatedFuture(value * 4);
            });
            x.promise.SetResult(100);
            Assert(f1.Result === 200);
            Assert(f2.Result === 400);
        })
    </script>
    <script>
        TestCase("a written failed result should be correctly redirected (1)", function () {
            var x = CreateDelay();
            var f1 = x.future.FailedThen(function (value) {
                return value * 2;
            });
            var f2 = x.future.Then(function (value) {
                Assert(DelayException.TestType(value));
                return value.Exception * 4;
            });
            x.promise.SetException(100);
            Assert(f1.Result === 200);
            Assert(f2.Result === 400);
        })
    </script>
    <script>
        TestCase("a written failed result should be correctly redirected (2)", function () {
            var x = CreateDelay();
            var f1 = x.future.FailedThen(function (value) {
                return CreateEvaluatedFuture(value * 2);
            });
            var f2 = x.future.Then(function (value) {
                Assert(DelayException.TestType(value));
                return CreateEvaluatedFuture(value.Exception * 4);
            });
            x.promise.SetException(100);
            Assert(f1.Result === 200);
            Assert(f2.Result === 400);
        })
    </script>
    <script>
        TestCase("ContinueWith should pass the result", function () {
            var x = CreateDelay();
            var f = x.future.ContinueWith(function (value) {
                return value * 2;
            });
            x.promise.SetResult(100);
            Assert(f.Result === 200);
        })
    </script>
    <script>
        TestCase("ContinueWith should pass the exception", function () {
            var x = CreateDelay();
            var f = x.future.ContinueWith(function (value) {
                return value * 2;
            });
            x.promise.SetException(100);
            Assert(f.Result.Exception === 100);
        })
    </script>
    <script>
        TestCase("exception should be converted to failed result (1)", function () {
            var x = CreateDelay();
            var f1 = x.future.SucceededThen(function (value) {
                throw value * 2;
            });
            var f2 = x.future.Then(function (value) {
                throw value * 4;
            });
            x.promise.SetResult(100);
            Assert(f1.Result.Exception === 200);
            Assert(f2.Result.Exception === 400);
        })
    </script>
    <script>
        TestCase("exception should be converted to failed result (2)", function () {
            var x = CreateDelay();
            var f1 = x.future.FailedThen(function (value) {
                throw value * 2;
            });
            var f2 = x.future.Then(function (value) {
                throw value.Exception * 4;
            });
            x.promise.SetException(100);
            Assert(f1.Result.Exception === 200);
            Assert(f2.Result.Exception === 400);
        })
    </script>
    <script>
        TestCase("WaitAll should success", function () {
            for (var i = 0; i <= 3; i++) {
                var ds = [CreateDelay(), CreateDelay(), CreateDelay()];
                for (var j = 0; j < i; j++) {
                    ds[j].promise.SetResult(j);
                }

                var f = WaitAll(ds.map(function (delay) { return delay.future; }));
                Assert(f.HasResult() === (i === 3));

                for (var j = i; j < 3; j++) {
                    ds[j].promise.SetResult(j);
                }
                Assert(f.HasResult() === true);

                Assert(f.Result.length === 3);
                for (var j = 0; j < 3; j++) {
                    Assert(f.Result[j] === j);
                }
            }
        })
    </script>
    <script>
        TestCase("WaitAny should success", function () {
            for (var i = 0; i < 3; i++) {
                {
                    var ds = [CreateDelay(), CreateDelay(), CreateDelay()];
                    ds[i].promise.SetResult(i);

                    var f = WaitAny(ds.map(function (delay) { return delay.future; }));
                    Assert(f.HasResult() === true);

                    Assert(f.Result.index === i);
                    Assert(f.Result.result === i);
                }
                {
                    var ds = [CreateDelay(), CreateDelay(), CreateDelay()];

                    var f = WaitAny(ds.map(function (delay) { return delay.future; }));
                    Assert(f.HasResult() === false);

                    ds[i].promise.SetResult(i);
                    Assert(f.HasResult() === true);

                    Assert(f.Result.index === i);
                    Assert(f.Result.result === i);
                }
            }
        })
    </script>
    <script>
        TestCase("RepeatFuture should success", function () {
            var counter = 0;

            function generator() {
                return CreateEvaluatedFuture(++counter);
            }

            function continueRepeating(value) {
                return value !== 100;
            }

            var f = RepeatFuture(generator, continueRepeating);
            Assert(f.HasResult() === true);
            Assert(f.Result.length === 100);
            for (var i = 0; i < 100; i++) {
                Assert(f.Result[i] === i + 1);
            }
        })
    </script>
    <script>
        SummaryTest();
    </script>
</body>
</html>
